config/routes.rb
RailsBootstrap::Application.routes.draw do
  root :to => 'application#index'

  resources :posts 

  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base

validates_presence_of :created_by, :title, :content

end

app/models/user.rb
#           User Schema             #
# ----------------------------------#
# t.string   "email"                #
# t.string   "password_digest"      #
# ----------------------------------#

class User < ActiveRecord::Base

  has_secure_password
  validates_presence_of :email, :password, :password_confirmation

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
      @all_posts = Post.all
    end

    # GET new_message_url
    def new
      @post = Post.new
    end

    # POST messages_url
    def create
      @post = Post.new(post_params)
      #TODO: Assign created_by to current user.
      @post.created_by = "Billy"
      if @post.save
        redirect_to post_path(@post)
      else
        raise "Post couldn't be saved."
      end
    end

    # GET message_url(:id => 1)
    def show
      @post = Post.find(params[:id])
      # find and return a specific message
    end

    # GET edit_message_url(:id => 1)
    def edit
      # return an HTML form for editing a specific message
    end

    # PUT message_url(:id => 1)
    def update
      # find and update a specific message
    end

    # DELETE message_url(:id => 1)
    def destroy
      # delete a specific message
    end

    private

    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params) 
    redirect_to user_path(@user.id)
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @all_users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.haml
Front page

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %button.close{:type => "button", "data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%header.navbar.navbar-fixed-top
  %nav.navbar-inner
    .container
      %ul.nav
        %li= link_to 'Home', root_path
        %li= link_to 'About', page_path('about')
        %li= link_to 'Posts', new_post_path
        %li= link_to 'Register', new_user_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Application Title"
      %meta{:content => content_for?(:description) ? yield(:description) : "Rails Bootstrap", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = csrf_meta_tags
  %body
    = render 'layouts/navigation'

    %main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  .inputs
    = f.input :title
    = f.input :content
  .actions
    = f.button :submit

app/views/posts/index.html.haml
puts @all_posts.inspect

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
= @post.inspect

app/views/users/new.html.haml
%h3 Make a new account!
= simple_form_for @user do |f|
  = f.input :email, :required => 'true'
  = f.input :password, :required => 'true'
  = f.input :password_confirmation, :required => 'true'
  = f.submit

app/views/users/show.html.haml
Thank you for creating an account!

= @user.inspect